### ISSUE TITLE
运行会闪退呀

### ISSUE THREAD

**Issue by LeeG4ng** [chuanggaofucker/ChuangGaoFuckerApp#1]

**Comment by chuanggaofucker** [comment]
请详细描述你遇到的问题。至少提供机型、闪退场景、如何复现。谢谢

**Comment by LeeG4ng** [comment]
机型：华为Mate 9/10  Vivo X9
场景：登录成功之后闪退（登录失败如密码错误的话会提示

**Comment by realZnCu** [comment]
> 
> 
> 请详细描述你遇到的问题。至少提供机型、闪退场景、如何复现。谢谢

我的机型是一加五，ROM 为 Mokee 9.0，编译好运行时也闪退，闪退时的界面为输好账号密码点击登录

![image](https://user-images.githubusercontent.com/29547263/54132665-9b4b0180-444f-11e9-97a9-49cfbe6e584d.png)

adb logcat 查到的日志如下：

03-11 22:25:27.789 15967 16080 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/net.crigh.cgsport-HBegwdKqEKV98vPAt_Tplg==/base.apk"],nativeLibraryDirectories=[/data/app/net.crigh.cgsport-HBegwdKqEKV98vPAt_Tplg==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libAMapSDK_Location_v6_6_0.so"

请问这里的 libAMapSDK_Location_v6_6_0.so 该怎么处理呢，多谢q(≧▽≦q)

**Comment by chuanggaofucker** [comment]
libAMapSDK_Location_v6_6_0.so 是原版app的一个动态库，之前忘记加上了。现在已经引入仓库。 @ZnCu-Shadow

**Comment by realZnCu** [comment]
> 
> 
> libAMapSDK_Location_v6_6_0.so 是原版app的一个动态库，之前忘记加上了。现在已经引入仓库。 @ZnCu-Shadow

好的，没有问题辽~
多谢o(*^＠^*)o
