### ISSUE TITLE
如何自定义跑步数据？js代码被压缩了看不懂

### ISSUE THREAD

**Issue by phoenixsfly** [chuanggaofucker/ChuangGaoFuckerApp#6]
看到源码NetWorkService中有一大段被注释的代码，修改其中的数据就行了嘛？

**Comment by chuanggaofucker** [comment]
network service有很长一段被uglify了的JavaScript代码，它的作用是生成随机跑步数据。你可以修改它。

**Comment by chuanggaofucker** [comment]
如果没有进一步疑问，这个issue我就关掉了🤪

**Comment by phoenixsfly** [comment]
能给出原始js代码吗？网上的解压缩工具都不好用啊
（毕竟不是JS选手ヾ(ﾟ∀ﾟゞ)
